### ISSUE TITLE
Search feature not working

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/cariin#1]
Please fix search feature in https://cariin.vercel.app/jobs#

**Comment by isnancahyadi** [comment]
I have fixed it. Thank You.
![Screenshot (151)](https://github.com/isnancahyadi/cariin/assets/97781402/45380686-2bf1-4f9b-a5b3-ec93af390205)

**Comment by kubil-ismail** [comment]
Done
<img width="1680" alt="Screenshot 2023-08-10 at 00 09 32" src="https://github.com/isnancahyadi/cariin/assets/49361887/3331f7b3-948e-4bfc-ab00-1188a8cfd1d8">
