### ISSUE TITLE
Error in send email feature

### ISSUE THREAD

**Issue by kubil-ismail** [isnancahyadi/cariin#2]
Error in send email feature, got response this
![Screenshot (122)](https://github.com/isnancahyadi/cariin/assets/49361887/4e964d1f-aaab-4230-b4d4-5df335166225)

**Comment by isnancahyadi** [comment]
I have fixed this. Thank You.
![WhatsApp Image 2023-08-08 at 17 16 30](https://github.com/isnancahyadi/cariin/assets/97781402/098fe9f4-cbdf-425b-af30-365c4f7095db)

**Comment by kubil-ismail** [comment]
done
<img width="1680" alt="Screenshot 2023-08-10 at 00 08 06" src="https://github.com/isnancahyadi/cariin/assets/49361887/40bf9446-b7b0-4edb-a35c-9d026d00a11d">
